proyecto_DJComponentes/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

#TEMPLATE TAGGING
app_name = "basic_app"

urlpatterns = [
    url(r'^$',views.home,name='home'),
    # REGISTRO
    url(r'^register/$',views.register,name='register'),
    # LOGIN
    url(r'^user_login/$',views.user_login,name='user_login'),
    # FAQ
    url(r'^support/$',views.support,name="support"),
    # CARRITO
    url(r'^carrito/$',views.carrito,name="carrito"),
    # CONSOLAS
    url(r'^consolas/$',views.consolas,name="consolas"),
    url(r'^consolas_xbox/$',views.consolas_xbox,name="consolas_xbox"),
    url(r'^consolas_playstation/$',views.consolas_playstation,name="consolas_playstation"),
    url(r'^consolas_nintendo/$',views.consolas_nintendo,name="consolas_nintendo"),
    # ORDENADORES
    url(r'^ordenadores/$',views.ordenadores,name="ordenadores"),
    url(r'^ordenadores_sobremesa/$',views.ordenadores_sobremesa,name="ordenadores_sobremesa"),
    url(r'^ordenadores_portatiles/$',views.ordenadores_portatiles,name="ordenadores_portatiles"),
    # PERIFÉRICOS
    url(r'^perifericos/$',views.perifericos,name="perifericos"),
    url(r'^perifericos_teclados/$',views.perifericos_teclados,name="perifericos_teclados"),
    url(r'^perifericos_ratones/$',views.perifericos_ratones,name="perifericos_ratones"),
    url(r'^perifericos_cascos/$',views.perifericos_cascos,name="perifericos_cascos"),
    # IMPRESORAS
    url(r'^impresoras/$',views.impresoras,name="impresoras"),
    url(r'^impresoras_tinta/$',views.impresoras_tinta,name="impresoras_tinta"),
    url(r'^impresoras_laser/$',views.impresoras_laser,name="impresoras_laser"),
    url(r'^impresoras_matriciales/$',views.impresoras_matriciales,name="impresoras_matriciales"),
    #VIDEOJUEGOS
    url(r'^videojuegos/$',views.videojuegos,name="videojuegos"),
    url(r'^videojuegos_xbox/$',views.videojuegos_xbox,name="videojuegos_xbox"),
    url(r'^videojuegos_playstation/$',views.videojuegos_playstation,name="videojuegos_playstation"),
    url(r'^videojuegos_ordenador/$',views.videojuegos_ordenador,name="videojuegos_ordenador"),
    url(r'^videojuegos_nintendo/$',views.videojuegos_nintendo,name="videojuegos_nintendo"),

]

proyecto_DJComponentes/proyecto_DJComponentes/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.urls import path
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.home,name='home'),
    url(r'basic_app/',include('basic_app.urls')),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'special/',views.special,name='special'),
]

proyecto_DJComponentes/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete = models.CASCADE)

    #additional classes (examples)
    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

proyecto_DJComponentes/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

proyecto_DJComponentes/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm,UserProfileInfoForm

#
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
# DIRECTORIO INICIAL HOME
def home(request):
    return render(request,'basic_app/home.html')

# PRUEBA
@login_required
def special(request):
    return HttpResponse("you are logged in, nice!")

# LOGOUT
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('home'))

# REGISTRO
def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.error,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'basic_app/registration.html',
                            {'user_form':user_form,
                            'profile_form':profile_form,
                            'registered':registered})

# LOGIN
def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('home'))

            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")

        else:
            print("Someone tried to login and failed!")
            print("Username: {} and password {}".format(username,password))
            return HttpResponse("invalid login details supplied")

    else:
        return render(request,'basic_app/login.html',{})

# SOPORTE AL CLIENTE
def support(request):
    return render(request,'basic_app/soporte.html')

# CARRITO
def carrito(request):
    return render(request,'basic_app/carrito.html')

# ORDENADORES
def ordenadores(request):
    return render(request,'basic_app/ordenadores.html')

def ordenadores_sobremesa(request):
    return render(request,'basic_app/ordenadores_sobremesa.html')

def ordenadores_portatiles(request):
    return render(request,'basic_app/ordenadores_portatiles.html')

# CONSOLAS
def consolas(request):
    return render(request,'basic_app/consolas.html')

def consolas_xbox(request):
    return render(request,'basic_app/consolas_xbox.html')

def consolas_playstation(request):
    return render(request,'basic_app/consolas_playstation.html')

def consolas_nintendo(request):
    return render(request,'basic_app/consolas_nintendo.html')

# PERIFÉRICOS
def perifericos(request):
    return render(request,'basic_app/perifericos.html')

def perifericos_teclados(request):
    return render(request,'basic_app/perifericos_teclados.html')

def perifericos_ratones(request):
    return render(request,'basic_app/perifericos_ratones.html')

def perifericos_cascos(request):
    return render(request,'basic_app/perifericos_cascos.html')

# IMPRESORAS
def impresoras(request):
    return render(request,'basic_app/impresoras.html')

def impresoras_tinta(request):
    return render(request,'basic_app/impresoras_tinta.html')

def impresoras_laser(request):
    return render(request,'basic_app/impresoras_laser.html')

def impresoras_matriciales(request):
    return render(request,'basic_app/impresoras_matriciales.html')

# VIDEOJUEGOS
def videojuegos(request):
    return render(request,'basic_app/videojuegos.html')

def videojuegos_xbox(request):
    return render(request,'basic_app/videojuegos_xbox.html')

def videojuegos_playstation(request):
    return render(request,'basic_app/videojuegos_playstation.html')

def videojuegos_ordenador(request):
    return render(request,'basic_app/videojuegos_ordenador.html')

def videojuegos_nintendo(request):
    return render(request,'basic_app/videojuegos_nintendo.html')

proyecto_DJComponentes/templates/basic_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <!-- <title>DJComp</title> -->
    <!-- Fuente Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bitter:wght@300&display=swap" rel="stylesheet">
    <!-- Bootstrap 5 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>

    <!-- CSS -->
    <link rel="stylesheet" href="{% static "css/estilo_banner.css" %}">
    <link rel="stylesheet" href="{% static "css/main.css" %}">
    <link rel="stylesheet" href="{% static "css/estilo_faq.css" %}">
    <link rel="stylesheet" href="{% static "css/categorias.css" %}">
    <link rel="stylesheet" href="{% static "css/subcategorias.css" %}">
    <link rel="stylesheet" href="{% static "css/registro_login.css" %}">
    <link rel="stylesheet" href="{% static "css/carrito.css" %}">
    <style>
      .hidden {
        display: none;
      }
    </style>
  </head>

  <body>
    <div id="banner_base" class="container-fluid" style="background-color: white;">
      <nav class="navbar navbar-expand-sm navbar-light">
        <a href="{% url 'home' %}" class="navbar-brand">
          <img src="{% static "images/Logo_DJComponentes.jpg" %}" alt="Logo DJComponentes" width="320" height="125"
          class="d-inline-block align-top" />
          <span class="hidden">DJComponentes</span>
        </a>
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#toggleMobileMenu"
            aria-controls="toggleMobileMenu"
            aria-expanded="false"
            aria-lable="Toggle navigation"
          >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="toggleMobileMenu">
          <ul class="navbar-nav ms-auto text-center align-top">
            <li>
              <a class="nav-link" href="{% url 'home' %}">Home</a>
            </li>
            <!-- <li>
              <a class="nav-link" href="{% url 'basic_app:consolas' %}"><b>Consolas</b></a>
            </li>
            <li>
              <a class="nav-link" href="{% url 'basic_app:ordenadores' %}"><b>Ordenadores</b></a>
            </li>
            <li>
              <a class="nav-link" href="{% url 'basic_app:perifericos' %}"><b>Periféricos</b></a>
            </li>
            <li>
              <a class="nav-link" href="{% url 'basic_app:videojuegos' %}"><b>Videojuegos</b></a>
            </li>
            <li>
              <a class="nav-link" href="{% url 'basic_app:impresoras' %}"><b>Impresoras</b></a>
            </li> -->

            {% if user.is_authenticated %}
            <li><a class='nav-link' href="{% url 'basic_app:carrito' %}"><b>Artículos</b></a> </li>
            <li>
              <a class="nav-link" href="#">Comentarios</a>
            </li>
            {% endif %}

            {% if user.is_anonymous %}
            <li><a class="nav-link" href="{% url 'basic_app:register' %}">Registro</a></li>
            {% endif %}

            {% if user.is_authenticated %}
            <li><a class='nav-link' href="{% url 'logout' %}">Logout</a> </li>

            {% else %}
            <li><a class='nav-link' href="{% url 'basic_app:user_login' %}">Login</a> </li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </div>
    <div class="">
      {% block body_block %}

      {% endblock %}
    </div>
    <!---FOOTER-INICIO--------------------------------------------->
    <div id="footer" class="p-5">
      <div class="container w-50 pt-5">
        <div class="row row-cols-md-2 justify-content-md-center">
          <div class="col text-center">
            <a href="{% url 'basic_app:support' %}">
              <button class="btn btn-lg rounded-pill btn-warning w-100 p-3 shadow-sm font-weight-bold"><b>Soporte al Cliente</b></button>
            </a>
          </div>
        </div>

        <div class="row justify-content-md-center py-2">
          <div class="col text-center font-weight-light"> <br>
            <p>Copyright 2022  -  DJComponentes</p>
            <p>C/ Atarazana, 2, 44003, Teruel  -  Escuela Universitaria Politécnica de Teruel</p>
            <p>Ingeniería Web - Front End</p>
          </div>
        </div>
      </div>
    </div>
    <!---FOOTER-FIN---------------------------------------------->
  </body>
</html>

proyecto_DJComponentes/templates/basic_app/consolas_playstation.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% load static %}
{% block body_block %}
<title>Consolas PS</title>
<div class="container">
  <!---BANNER-INICIO--------------------------------------------->
  <div id="banner_consolas_nintendo" class="p-5" background-size="full-width">
    <div class="container">
      <div class="jumbotron">
        <div class="row justify-content-md-left py-2">
          <h1><b>Consolas PlayStation</b></h1>
          <p>
            Nada como la sensación de llegar a casa, ponerse bien cómod@, encender la televisión y pasar un buen rato acompañados de nuestra <b>PlayStation 4</b>. Para hacer tu experiencia todavía mejor, combínala con los mejores juegos para PS4. ¿Conoces la maravillosa vida de un/a jugador/a de PS4? ¿No? ¡Pues ya es hora de que adquieras una <b>PlayStation 4</b>!
            <br>
            En DJComponentes también podrás encontrar los mejores packs de <b>PlayStation 5</b> al mejor precio, con el juego que te gusta o con dos mandos, para jugar con amigos.
          </p>
        </div>
      </div>
    </div>
  </div>
  <!---BANNER-FIN---------------------------------------------->
</div>
{% endblock %}

proyecto_DJComponentes/templates/basic_app/impresoras.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% load static %}
{% block body_block %}
<title>Impresoras</title>
<div class="container">
  <!---BANNER-INICIO--------------------------------------------->
  <div id="banner_impresoras" class="p-5" background-size="full-width">
    <div class="container">
      <div class="jumbotron">
        <div class="row justify-content-md-left py-2">
          <h1><b>Impresoras</b></h1>
          <p>Accede a nuestros productos como tintas y tóners o a nuestra selección de impresoras o multifunciones.</p>
          <br><br>
          <img src="..\..\static\images\impresoras_banner_1.png" class="mx-auto d-block" alt="foto_banner" id="banner_impresoras_img_type2">
          <img src="..\..\static\images\impresoras_banner_2.png" class="mx-auto d-block" alt="foto_banner" id="banner_impresoras_img_type1">
          <!-- <img src="..\..\static\images\impresoras_banner_3.png" class="mx-auto d-block" alt="foto_banner" id="banner_impresoras_img_type1"> -->
          <img src="..\..\static\images\impresoras_banner_4.png" class="mx-auto d-block" alt="foto_banner" id="banner_impresoras_img_type1">
          <!-- <img src="..\..\static\images\impresoras_banner_5.png" class="mx-auto d-block" alt="foto_banner" id="banner_impresoras_img_type1"> -->
          <img src="..\..\static\images\impresoras_banner_6.png" class="mx-auto d-block" alt="foto_banner" id="banner_impresoras_img_type1">
        </div>
      </div>
    </div>
  </div>
  <!---BANNER-FIN---------------------------------------------->

  <!---SUBCATEGORÍAS-INICIO---------------------------------------------->
  <div id="subcategorias_impresoras">
    <div class="container-md p-5">
      <div class="row">

        <div class="col-sm">
          <a href="{% url 'basic_app:impresoras_tinta' %}">
            <div class="card w-100 card-border mb-5" id="subcategorias_impresoras_tinta">
              <img class="card-img-top" src="..\..\static\images\subcategorias_ordenadores_sobremesa.png" alt="Card image 1">
              <div class="card-body">
                <h4 class="card-title"><b>Impresoras de tinta</b></h5>
                <p class="card-text"></p>
              </div>
            </div>
          </a>
        </div>

        <div class="col-sm">
          <a href="{% url 'basic_app:impresoras_laser' %}">
            <div class="card w-100 card-border mb-5" id="subcategorias_impresoras_laser">
              <img class="card-img-top" src="..\..\static\images\subcategorias_ordenadores_sobremesa.png" alt="Card image 2">
              <div class="card-body">
                <h4 class="card-title"><b>Impresoras láser</b></h5>
                <p class="card-text"></p>
              </div>
            </div>
          </a>
        </div>

        <div class="col-sm">
          <a href="{% url 'basic_app:impresoras_matriciales' %}">
            <div class="card w-100 card-border mb-5" id="subcategorias_impresoras_matriciales">
              <img class="card-img-top" src="..\..\static\images\subcategorias_ordenadores_sobremesa.png" alt="Card image 3">
              <div class="card-body">
                <h4 class="card-title"><b>Impresoras matriciales</b></h5>
                <p class="card-text"></p>
              </div>
            </div>
          </a>
        </div>

      </div>
    </div>
  </div>
  <!---SUBCATEGORÍAS-FIN---------------------------------------------->
</div>
{% endblock %}

proyecto_DJComponentes/templates/basic_app/impresoras_laser.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% load static %}
{% block body_block %}
<title>Impresoras láser</title>
<div class="container">
  <!---BANNER-INICIO--------------------------------------------->
  <div id="banner_impresoras_laser" class="p-5" background-size="full-width">
    <div class="container">
      <div class="jumbotron">
        <div class="row justify-content-md-left py-2">
          <h1><b>Impresoras láser</b></h1>
          <p>Las impresoras láser no derrochan tinta, usan tinta en polvo y
            pulverizan la superficie de papel, logrando un acabado nítido y
            brillante. Esto logra que la impresión salga prácticamente seca y
            se evitan borrones no deseados. Este tipo de impresoras no usan
            cartuchos, sino tóners. Una impresora láser es siempre una buena
            opción cuando se suele imprimir asiduamente, ya que el precio por
            copia impresa suele ser muy inferior al de las impresoras de
            inyección de tinta. Hazte con tu impresora láser o multifunción.
          </p>
        </div>
      </div>
    </div>
  </div>
  <!---BANNER-FIN---------------------------------------------->
</div>
{% endblock %}

proyecto_DJComponentes/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
{% block body_block %}
<title>Login</title>
<div class="jumbotron">
  <br><h1 id="login_titulo"><center>¡Inicia sesión!</center></h1><br><br>
  <form action="{% url 'basic_app:user_login' %}" method="post" class="container pl-5 rounded-lg" id="reg_form">
    {% csrf_token %}
    <br><center><label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter Username">

    <label for="password">Password:</label>
    <input type="password" name="password">

    <input type="submit" name="" value="Login"></center>

  </form>

</div>

{% endblock %}

proyecto_DJComponentes/templates/basic_app/perifericos.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% load static %}
{% block body_block %}
<title>Periféricos</title>
<div class="container">
  <!---BANNER-INICIO--------------------------------------------->
  <div id="banner_perifericos" class="p-5" background-size="full-width">
    <div class="container">
      <div class="jumbotron">
        <div class="row justify-content-md-left py-2">
          <h1><b>Periféricos</b></h1>
          <p>Un ordenador potente no es nada sin todos los periféricos que le rodean. Teclados, ratones y también una amplia gama de auriculares. Son tan básicos y necesarios que muchas veces pensamos que forman parte del ordenador.</p>
          <br>

          <img src="..\..\static\images\perifericos_banner2.png" class="mx-auto d-block" alt="foto_banner" id="banner_perifericos_img_type1">
          <!-- <img src="..\..\static\images\perifericos_banner3.png" class="mx-auto d-block" alt="foto_banner"> -->
          <img src="..\..\static\images\perifericos_banner1.png" class="mx-auto d-block" alt="foto_banner" id="banner_perifericos_img_type2">
          <img src="..\..\static\images\perifericos_banner5.png" class="mx-auto d-block" alt="foto_banner" id="banner_perifericos_img_type2">
          <img src="..\..\static\images\perifericos_banner4.png" class="mx-auto d-block" alt="foto_banner" id="banner_perifericos_img_type3">

          <!-- <img src="..\..\static\images\perifericos_banner6.png" class="mx-auto d-block" alt="foto_banner">
          <img src="..\..\static\images\perifericos_banner7.png" class="mx-auto d-block" alt="foto_banner">
          <img src="..\..\static\images\perifericos_banner8.png" class="mx-auto d-block" alt="foto_banner">
          <img src="..\..\static\images\perifericos_banner9.png" class="mx-auto d-block" alt="foto_banner"> -->
        </div>
      </div>
    </div>
  </div>
  <!---BANNER-FIN---------------------------------------------->

  <!---SUBCATEGORÍAS-INICIO---------------------------------------------->
  <div id="subcategorias_perifericos">
    <div class="container-md p-5">
      <div class="row">

        <div class="col-sm">
          <a href="{% url 'basic_app:perifericos_teclados' %}">
            <div class="card w-100 card-border mb-5" id="subcategorias_perifericos_teclados">
              <img class="card-img-top" src="..\..\static\images\subcategorias_ordenadores_sobremesa.png" alt="Card image 1">
              <div class="card-body">
                <h4 class="card-title"><b>Teclados</b></h5>
                <p class="card-text"></p>
              </div>
            </div>
          </a>
        </div>

        <div class="col-sm">
          <a href="{% url 'basic_app:perifericos_ratones' %}">
            <div class="card w-100 card-border mb-5" id="subcategorias_perifericos_ratones">
              <img class="card-img-top" src="..\..\static\images\subcategorias_ordenadores_sobremesa.png" alt="Card image 2">
              <div class="card-body">
                <h4 class="card-title"><b>Ratones</b></h5>
                <p class="card-text"></p>
              </div>
            </div>
          </a>
        </div>

        <div class="col-sm">
          <a href="{% url 'basic_app:perifericos_cascos' %}">
            <div class="card w-100 card-border mb-5" id="subcategorias_perifericos_cascos">
              <img class="card-img-top" src="..\..\static\images\subcategorias_ordenadores_sobremesa.png" alt="Card image 3">
              <div class="card-body">
                <h4 class="card-title"><b>Auriculares</b></h5>
                <p class="card-text"></p>
              </div>
            </div>
          </a>
        </div>

      </div>
    </div>
  </div>
  <!---SUBCATEGORÍAS-FIN---------------------------------------------->
</div>
{% endblock %}

proyecto_DJComponentes/templates/basic_app/videojuegos.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% load static %}
{% block body_block %}
<title>Videojuegos</title>
<div class="container">
  <!---BANNER-INICIO--------------------------------------------->
  <div id="banner_videojuegos" class="p-5" background-size="full-width">
    <div class="container">
      <div class="jumbotron">
        <div class="row justify-content-md-left py-2">
          <h1><b>Videojuegos</b></h1>
          <p>Las últimas novedades y juegos clásicos a un precio increíble. En físico, y ahora también en digital (códigos de descarga). Disfruta de una gran variedad de títulos y ediciones coleccionista de los últimos lanzamientos y mejores juegos. Si eres de los que les gusta quedar con amigos para jugar, aquí tienes un montón de mandos y otros accesorios. ¡Para vosotros, jugadores!</p>
          <br><br><br><br><br>
          <img src="..\..\static\images\videojuegos_banner1.png" class="mx-auto d-block" alt="foto_banner" id="banner_videojuegos_img_type4">
          <img src="..\..\static\images\videojuegos_banner3.png" class="mx-auto d-block" alt="foto_banner" id="banner_videojuegos_img_type1">
          <img src="..\..\static\images\videojuegos_banner4.png" class="mx-auto d-block" alt="foto_banner" id="banner_videojuegos_img_type2">
          <img src="..\..\static\images\videojuegos_banner2.png" class="mx-auto d-block" alt="foto_banner" id="banner_videojuegos_img_type3">
          <!-- <img src="..\..\static\images\videojuegos_banner5.png" class="mx-auto d-block" alt="foto_banner"> -->
        </div>
      </div>
    </div>
  </div>
  <!---BANNER-FIN---------------------------------------------->
  <!---SUBCATEGORÍAS-INICIO---------------------------------------------->
  <div id="subcategorias_videojuegos">
    <div class="container-md p-5">
      <div class="row">

        <div class="col-sm">
          <a href="{% url 'basic_app:videojuegos_xbox' %}">
            <div class="card w-100 card-border mb-5" id="subcategorias_videojuegos_xbox">
              <img class="card-img-top" src="..\..\static\images\subcategorias_ordenadores_sobremesa.png" alt="Card image 1">
              <div class="card-body">
                <h4 class="card-title"><b>Para XBOX</b></h5>
                <p class="card-text"></p>
              </div>
            </div>
          </a>
        </div>

        <div class="col-sm">
          <a href="{% url 'basic_app:videojuegos_playstation' %}">
            <div class="card w-100 card-border mb-5" id="subcategorias_videojuegos_playstation">
              <img class="card-img-top" src="..\..\static\images\subcategorias_ordenadores_sobremesa.png" alt="Card image 2">
              <div class="card-body">
                <h4 class="card-title"><b>Para PlayStation</b></h5>
                <p class="card-text"></p>
              </div>
            </div>
          </a>
        </div>

        <div class="col-sm">
          <a href="{% url 'basic_app:videojuegos_ordenador' %}">
            <div class="card w-100 card-border mb-5" id="subcategorias_videojuegos_ordenador">
              <img class="card-img-top" src="..\..\static\images\subcategorias_ordenadores_sobremesa.png" alt="Card image 3">
              <div class="card-body">
                <h4 class="card-title"><b>Para PC</b></h5>
                <p class="card-text"></p>
              </div>
            </div>
          </a>
        </div>

        <div class="col-sm">
          <a href="{% url 'basic_app:videojuegos_nintendo' %}">
            <div class="card w-100 card-border mb-5" id="subcategorias_videojuegos_nintendo">
              <img class="card-img-top" src="..\..\static\images\subcategorias_ordenadores_sobremesa.png" alt="Card image 4">
              <div class="card-body">
                <h4 class="card-title"><b>Para Nintendo</b></h5>
                <p class="card-text"></p>
              </div>
            </div>
          </a>
        </div>

      </div>
    </div>
  </div>
  <!---SUBCATEGORÍAS-FIN---------------------------------------------->
</div>
{% endblock %}